default_language_version:
  python: python3.8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-submodules
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: pretty-format-json
  - id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.1.1
  hooks:
  - id: black

- repo: https://github.com/hadialqattan/pycln
  rev: v2.3.0
  hooks:
  - id: pycln
    args: ["--config=pyproject.toml"]

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: ["--max-line-length=88", "--extend-ignore=E203,E704"]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
    - -rn # Only display messages
    - -sn # Don't display the score

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types_or: [python, pyi]
    require_serial: true
